### ISSUE TITLE
Origins don't work for me, when i want to join my server.

### ISSUE THREAD

**Issue by HeinzShultz** [apace100/origins-fabric#116]
Sup. I have a problem. Origins mod don't work for me, when i want to join my minecraft server, hosted on ,,Apex Hosting''. Whe i'm on my server list, it seems ok. The server is here, and it looks like i can join it. When i'm joining the server, it says ,,connection lost''. I contacted with the server support. After a long talk, they told me to put my issue here, because it can be mod error. 
My friend also tried to join my server, but he had the same thing, so i don't think that is mod fault at all. 
That's all, i hope that somebody help me solve my problem :) .

**Comment by apace100** [comment]
This is probably the issue caused by using a different Origins version on the client and the server.
So, please make sure that the Origins on your server is the same version (e.g. 0.4.7) as the one you and your friend are using.

If that is the case, feel free to reply here (with posting log files of client and server) and I'll reopen the issue.
