### ISSUE TITLE
Phantom Balance Change

### ISSUE THREAD

**Issue by LukeWarmS0up** [apace100/origins-fabric#121]
Full invisibility is very strong but lack of armor mostly invalidates it so I recommend particles rendering while wearing armor and a tagging feature where players receive the glow effect while phantomized if hit by players

**Comment by apace100** [comment]
For now, I think I won't implement these ideas. Thanks for posting them though. :)
I'm happy with the balancing of the Phantom's invisibility power and think that the vanilla mechanic of armor still being visible is a good tradeoff. Also, it would add unnecessary complexity, because the Phantom's description would have to explain the differences between the Phantom invisibility and the regular invisibility if I made these changes, which I don't think is a good thing.
