### ISSUE TITLE
Do the "execute command" work or am I dumb ?

### ISSUE THREAD

**Issue by Rwstix** [apace100/origins-fabric#123]
I'm trying to make a origin named Jester which goal is to trick my friends. So i decided to create a power which will make a large fog effect cloud of blindness. I've tried the command by typing it in chat and it works perfectly fine. So why is the origin not showing ? I've tried to launch the datapack without this power and it works. So where is the problem ?

If someone see what is the problem, please tell me ! 

![jesterprob2](https://user-images.githubusercontent.com/79268223/108630314-0a01a980-7432-11eb-8562-917131f42841.PNG)
![jesterprob1](https://user-images.githubusercontent.com/79268223/108630315-0a01a980-7432-11eb-9c55-87b73b8210d3.PNG)

**Comment by apace100** [comment]
The problem is that JSON has trouble parsing your command this way.
This is because the quotes (") are used to determine the beginning and end of a field in JSON, and in your case, the command also contains ". If you think about this like a machine, you'll see that the only thing which would be the "command" you specify is the following: `summon area_effect_cloud ~ ~ ~ {Particle:` (Everything from " to ")

To prevent this from happening, you need to _escape_ quotes which appear in your command. You can do this by adding a \ before them: `summon area_effect_cloud ~ ~ ~ {Particle:\"crimson_spore\",Radius:5f,Duration:200,Effects:[{Id:15b,Amplifier:2b,Duration:200,ShowParticles:1b}]}`
