### ISSUE TITLE
Make Shulk More Interesting

### ISSUE THREAD

**Issue by Zachattack525** [apace100/origins-fabric#168]
As of right now, I find the Shulk origin to be severely bland and underwhelming, with half of its benefit being irrelevant in hardcore. the Shulk origin feels like it has nothing to do with shulkers, so I want to propose something to make them a bit more interesting:

Shulks are naturally small and very squishy but have the ability to burrow into blocks and turn them into a shell, functioning just like a real shulker would, being able to open and close the shell (levitation projectile is debatable.) if the block burrowing thing is a bit too much there is the option of having them simply form a shell around themself.

their mostly sedentary lifestyle would mean that they do require more hunger. perhaps they're vegetarian.

perhaps as a visual thing, they become just the player's head.

people can add more suggest more ideas as well. I just really want to see the Shulk be more interesting.

**Comment by apace100** [comment]
I think the Shulk origin will stay as it is for a while. However I do see why you feel that it is a bit "bland" - after all it is a low impact origin and is not supposed to change the gameplay drastically.

"half of its benefit being irrelevant in hardcore" is not quite true imo, the 9 extra inventory slots are still very helpful (even if you're not making use of the "save on death" functionality), the armor is still very helpful (and can be argued to be even more helpful in hardcore) and the stone mining remains a nice tool early on and is unchanged even in that game mode. 

"nothing to do with shulkers" is also something I have to disagree with. The additional protection comes from the Shulker's shell (changed to constant armor instead of some switch between "being in the shell and having protection" and "being out of the shell and vulnerable" for simplicity, making it easier to play and keeping it low impact), and the inventory space was inspired by Shulker boxes.

With the above reasoning, I'm gonna close this issue. However I do appreciate your feedback and ideas a lot and am definitely coming back to think about these if I decide to change the Shulk origin at some point in the future. :)
