### ISSUE TITLE
Idea for Shulk race

### ISSUE THREAD

**Issue by AwesomeAri** [apace100/origins-fabric#175]
(This isn't a bug or an issue, but just a suggestion that I thought would be cool, as a heads up)
With the Shulk, I don't think that it makes sense when the fist of the shulk is strong enough to break cobble on it's own, but that strength doesn't do anything else ( like increasing the speed of which you can break blocks, for example) and it also doesn't do anything when combined with other tools (Like if you use a stone pickaxe, it works as stone pickaxe like normal instead of adding the strength of the Shulk to increase breaking speed, or making it so that it can mine other materials which it normally wouldn't be able to, like diamonds. I feel like changing this would make the game a lot more fun, and it would work better with the race.

**Comment by apace100** [comment]
After some thought, I see the logic behind your suggestion, however I don't think the Shulk needs it, since it is already quite strong, and being able to mine all blocks faster would make it an incredible choice for many types of players. The block breaking speed bonus it has is really just there to acommodate the "harvest stone without tool" power, and make that not feel completely terrible (because you know the speed of breaking stone with a fist when you're not a Shulk ;)). Therefore I've decided not to change this any time soon and will close the issue.
