### ISSUE TITLE
Weird Bungee Bug

### ISSUE THREAD

**Issue by 13ERT** [apace100/origins-fabric#186]
Hello, I have noticed that if you run the origins mod on Velocity bungee when connecting to the server It will give an error:
'This server requires you to install the Origins mod (v0.5.2) to play.'

Alothough both the client and the serevr has the same mods and right versions
I looked for help on the discord and one of the devs for velocity said its mod specific

**Comment by BootSwitch** [comment]
Only happens with 0.5.0+. I was using 0.4.7 fine, but when I updated to 0.6.0 everything went wrong.

**Comment by 13ERT** [comment]
Solution in new update

**Comment by TMShader** [comment]
The new update (v0.6.2) still rejects players if used with a Velocity proxy server. I tried tinkering with the player info forwarding methods but it didn't seem to fix the problem.

**Comment by 13ERT** [comment]
You need to disable verification in the config

**Comment by TMShader** [comment]
I tried that but it still gives an error

**Comment by TMShader** [comment]
This is the the error I get whenever I try to join:
![image](https://user-images.githubusercontent.com/43723765/112020752-e87b0700-8b30-11eb-88b2-85ac28c6f0f4.png)

Also these are the mods that we are using:
![image](https://user-images.githubusercontent.com/43723765/112020994-211ae080-8b31-11eb-9d56-434fea4d116c.png)

**Comment by apace100** [comment]
That error seems to be caused by Haema, not by Origins. I suggest opening an issue on their GitHub: https://github.com/williambl/haema/issues

**Comment by TMShader** [comment]
I wanted to check if that happened if i wasn't connecting with the proxy, but I forgot. I'll check now and get back to you.

**Comment by TMShader** [comment]
It seems like thats the isssue. Thanks for the help!

**Comment by MMIndustries** [comment]
I have the same symptoms. I am not using Haema.

Velocity proxy and a Fabric server. Origins 1.16.6-0.7.0, fabric to 0.7.3. "This server requires you to install the Origins mod (v0.7.0) to play".  With velocity disabled I can connect directly to the fabric server without error. I'm using "modern" forwarding. An un-modded paper server works perfectly.

Here's what I have:
  Velocity-1.1.4 plugins:
  FabricProxy-Lite-1.1.1.jar
  Advanced-Portals-0.5.1.-snapshot.jar

fabric-0.7.3 mods:
  fabric-api-0.33.0+1.16.jar
  FabricProxy-lite-1.1.1.jar
  Origins-1.16.5-0.7.0.jar
  extraorigins-1.16.5-11.jar
  Pehkui-2.0.0+21w14a.jar
  vanilladeathchest-1.16.3-1.11.0.7-fabric.jar

client:
  fabric-api-0.33.0+1.16.jar
  Origins-1.16.5-0.7.0.jar
  extraorigins-1.16.5-11.jar
  Pehkui-2.0.0+21w14a.jar

Others have indicated that the version check that origin is using in not compatible with proxies since the Proxy doesn't know what mod versions the clients are using.

**Comment by BootSwitch** [comment]
You can disable the version check in the configuration in latest versions.
