### ISSUE TITLE
unable to select origins on first world join

### ISSUE THREAD

**Issue by LordDecay26** [apace100/origins-fabric#206]
cannot determine the source of the issue, posting here in case the source is a bug with the mod itself, or an incompatibility with any number of it's add-ons, or a separate mod entirely. please help me resolve this issue. 
[latest.log](https://github.com/apace100/origins-fabric/files/6136651/latest.log)

**Comment by Noaaan** [comment]
It seems that the origin layer might be experiencing some issue with Requiem. You could try disabling it and see if it causes the issue.

**Comment by LordDecay26** [comment]
the requiem version has not changed, the previous version of the modpack works just fine, and it has requiem. it was only after updating that the issue reared it's ugly head.

**Comment by MineRobber9000** [comment]
```
[08:21:48] [main/ERROR]: There was a problem reading Origin layer file requiem:soul_type (skipping): JsonSyntaxException: EntityCondition json type "requiem:start_remnant_gamerule" is not defined.
...
[08:21:48] [main/ERROR]: There was a problem reading Origin layer file origins:origin (skipping): JsonSyntaxException: JsonSyntaxException: EntityCondition json type "requiem:start_remnant_gamerule" is not defined.
```

Interesting. Try reinstalling Requiem?

**Comment by apace100** [comment]
Yes, this seems to have been an issue with one of the add-ons (namely Requiem) which probably was incompatible due to an update I made and it wasn't updated yet. I hope that is resolved by now if you have updated to the newest versions. Sorry for taking so long for answering.
I'm closing the issue now, however if the problem still persists please feel free to leave another comment and I'll reopen it.
