### ISSUE TITLE
connection lost

### ISSUE THREAD

**Issue by Jagokb** [apace100/origins-fabric#209]
Hi, I have seen that some other people had the same problem as this can't connect to the world. Got a "Connection Lost" message directly after "Loading Terrain" message shows up. and that the solution is it needs to be on the same version as the launcher but I do not understand how to do that and how or find where are the different versions are.

could you help?

**Comment by Jagokb** [comment]
pls help!

**Comment by apace100** [comment]
Are you playing on a server or on singleplayer?
Are you using any data packs?
Could you share a log from your client?

**Comment by Jagokb** [comment]
I am on a server and I am not using a data pack but how do I share a log

**Comment by Jagokb** [comment]
?

**Comment by apace100** [comment]
Since your playing on the server, this is _very likely_ the version issue. Ask your server owner which Origins version they are using. Then make sure to install exactly that version on your client. You can find all of the Origins versions on this page: https://www.curseforge.com/minecraft/mc-mods/origins/files

For more help, please visit the Discord server, because you'll get more immediate help there.
