### ISSUE TITLE
Consider for a recipe for Orb of Origin?

### ISSUE THREAD

**Issue by teddyxlandlee** [apace100/origins-fabric#21]
There's no recipe for Orb of Origin now, that players couldn't regret their choice at the beginning of the game. However, a recipe for such a thing should be expensive.<br />
Here's my recipe for 1.16.1:<br />
□I□<br />
IAI<br />
□I□<br />
□: None;<br />I: Netherite Ingot;<br />A: Nether Star<br /><br />
If you think it's too expensive, you can change the Nether Star to Heart of the Sea, or change Netherite Ingot to Netherite Scrap.

**Comment by apace100** [comment]
The orb of origin not having a recipe is intentional. The origin being unchangeable is true to the idea of the mod, but at the same time I see why people would want the orb to be obtainable. That's why I encourage people to add their own recipe via a data pack, as I don't want to prescribe how expensive or cheap the orb should be. I've heard of people making the orb quite expensive with a Nether Star as the ingredient like you proposed, but I also heard of others who added a recipe that was way cheaper.

I hope this sufficiently explains why there's no recipe for the orb by default.
