### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by barbaralive** [apace100/origins-fabric#218]
I have a question. What if I installed and joined an existing normal world with this mod (same thing with the origin classes)? For ex : i have a plain normal world without any mod , what if I joined that world with this mod? Will it worked or what?

**Comment by apace100** [comment]
Yes, that will work. You’ll get to choose an origin when you join the world, just as it would work with a new one. Same with the classes add-on (even if you install that after you already played with just the regular Origins mod). Von: barbaraliveGesendet: Dienstag, 23. März 2021 07:22An: apace100/origins-fabricCc: SubscribedBetreff: [apace100/origins-fabric] Installing (#218) I have a question. What if I installed and joined an existing normal world with this mod (same thing with the origin classes)? For ex : i have a plain normal world without any mod , what if I joined that world with this mod? Will it worked or what?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
