### ISSUE TITLE
Latest Version Crash 1.16.5

### ISSUE THREAD

**Issue by lartts** [apace100/origins-fabric#222]
Crash when launching game
[latest.log](https://github.com/apace100/origins-fabric/files/6211339/latest.log)

**Comment by apace100** [comment]
This seems to be an incompatibility with one of the other mods you have installed. To figure out which one it is, I suggest removing half of your mods, and seeing whether the problem persists or not. If it does, you know that the problem is with one of the mods you didn't remove, but if the problem is gone you'll know it's one of those instead. You can then continue removing half of those mods which could be the problem, and do this until you've figured out exactly which mod it is.

**Comment by lartts** [comment]
Okay then

**Comment by lartts** [comment]
Found it, tic-tacs seems to be the reason lmao
