### ISSUE TITLE
quick cooldown bug

### ISSUE THREAD

**Issue by Latokike** [apace100/origins-fabric#227]
If you just used a cooldown on an origin with a long cooldown, you can switch to human or an origin with a short cooldown and after the cooldown is done, switch back to the original origin and their cooldown wont have to recharge

**Comment by apace100** [comment]
When switching origins, all powers and their data is removed. That means also cooldowns will be removed. This has nothing to do with a shorter cooldown running on your other origin, it just happens as a side effect of the origin change itself.
I have no intention to change this, because changing origins is not something I'm balancing around - it's not intended to be used in the truest sense of the mod (which is also why the Orb of Origins is not obtainable without installing a data pack for it).
