### ISSUE TITLE
Stackable water bottles for merling

### ISSUE THREAD

**Issue by C0DEHADES** [apace100/origins-fabric#228]
I still believe that depending on water bottles and respiration 3 for going to nether is really difficult. I came to achieve it, but as well I lost my sanity. And you even mentioned me one comment once about using respiration 3 and water bottles, but I believe this is still really hard as you need to literally depend on RNG to spawn in a fortress. So I was thinking that an indirect buff such as making only water bottles stackable would be enough to not lose sanity through the whole process.

**Comment by apace100** [comment]
There's also the turtle helmet which helps with this.
Honestly, Merling's only weakness is their limited breath on land, and there are already soooo many ways to mitigate that weakness, that I really don't think making it even easier is a good choice. The fact that you can use water bottles also is more a gimmick than a real feature - it was added afterwards for "logical" or "consistency" reasons because people asked for it, without the intention of making it much easier for Merlings.
