### ISSUE TITLE
Make choose origins box wider. Add scroll bar to let users know there is more text below.

### ISSUE THREAD

**Issue by RDKRACZ** [apace100/origins-fabric#235]
- descriptions are hard to read and long because of the current width.

![image](https://user-images.githubusercontent.com/43277609/113519859-33fcce80-958f-11eb-90e4-6007a873133d.png)
![image](https://user-images.githubusercontent.com/43277609/113519866-46770800-958f-11eb-82d9-391eff8774d6.png)

- my friend pointed out that at first, he thought this is all

![image](https://user-images.githubusercontent.com/43277609/113519925-c7ce9a80-958f-11eb-9f7f-bda0829d89a8.png)

but there is more, you just need to scroll down. Something should indicate this.

![image](https://user-images.githubusercontent.com/43277609/113519946-fba9c000-958f-11eb-9565-eed434cf94ef.png)

**Comment by apace100** [comment]
I disagree with making the box wider. The GUI behaves like any Minecraft gui - if you change your GUI scale it will become smaller. You'll have to play with a larger GUI scale setting if you want your GUIs to be large.

However I see the second issue (not knowing the box is scrollable), which is why I'll leave this issue open and label it as enhancement.

**Comment by apace100** [comment]
A scroll bar has been added in version 1.1.0
