### ISSUE TITLE
Can't connect through Velocity proxy

### ISSUE THREAD

**Issue by MMIndustries** [apace100/origins-fabric#261]
I have a Velocity proxy and a Fabric server. When I upgraded origins to 1.16.6-0.7.0 I had to upgrade fabric to 0.7.3. I can no longer connect to the fabric server. "This server requires you to install the Origins mod (v0.7.0) to play".  With velocity disabled I can connect directly to the fabric server without error. I'm using "modern" forwarding. An un-modded paper server works perfectly.

Here's what I have:
**Velocity-1.1.4** plugins: FabricProxy-Lite-1.1.1.jar Advanced-Portals-0.5.1.-snapshot.jar
**fabric-0.7.3** mods: fabric-api-0.33.0+1.16.jar FabricProxy-lite-1.1.1.jar Origins-1.16.5-0.7.0.jar extraorigins-1.16.5-11.jar Pehkui-2.0.0+21w14a.jar vanilladeathcest-1.16.3-1.11.0.7-fabric.jar
**client:** fabric-api-0.33.0+1.16.jar Origins-1.16.5-0.7.0.jar extraorigins-1.16.5-11.jar Pehkui-2.0.0+21w14a.jar

With the Origins mod removed connections work without problem.

**Comment by apace100** [comment]
Yes, this happens because of the version check (which you mentioned in the already closed issue).

You'll need to set an extra flag in the `origin_server.toml` configuration, namely `performVersionCheck = false`. This way, Origins doesn't check for the version and will connect anyway, which prevents this problem with proxy servers.

**Comment by D4rkma77er** [comment]
How do you acess these settings I cna't find it
