### ISSUE TITLE
Server Bug

### ISSUE THREAD

**Issue by redstonerblast** [apace100/origins-fabric#3]
Hey if you wanna join my server and play it, fine but anyway on to the bug.
It seems like once people are offline for a bit certain attributes stop working such as high jump for felines and other passive ones. I don't wanna keep giving my players the orb of origin to fix it either.

**Comment by apace100** [comment]
Thanks for the report. I think I have identified the problem, will push a fix in a bit (along with some fixes to the Elytrian) which you should only need to put on your server. Clients should work fine on your server if they have the older version.

Because I'm not sure if this really was your problem, please report back whether the issue still occurs. If it does, it would be helpful if you could include log files both from the client experiencing the bug and the server. If it doesn't, I will go ahead and close this issue.

**Comment by apace100** [comment]
I'm going to assume your problem is fixed now. If not, please comment again or open another issue. :)
