### ISSUE TITLE
Execute command value with datapacks

### ISSUE THREAD

**Issue by LurkingFox6539** [apace100/origins-fabric#308]
Not sure if this is an issue with the way I'm writing it, the mod, JSON, or something else, but when I use the execute command value as an entity action in custom datapacks, adding any nbt values makes it not work.

`"command": "summon minecraft:armor_stand ~ ~ ~"`

this works just fine, it summons the armor stand where I'm standing, but when I add some nbt's like this:

`"command": "summon minecraft:armor_stand ~ ~ ~ {Unbreakable:1b,NoGravity:1b,Tags:["positionStore"],Invisible:1b}"`

the power stops working and doesn't show up.
This might be an issue with JSON itself trying to make objects instead of maintaining the string but I was hoping there was a way with either syntax or something in the mod itself to fix this.

Edit: I was having a similar issue with descriptions containing quotations, I managed to bypass it by using escape sequences though, maybe this will work elsewhere? I'll test and edit later if so.

Edit: Disregard this, it was the quotation marks ending the string before I wanted it to, just using the `\"` escape sequence for it completely fixed the issue

**Comment by apace100** [comment]
You need to escape quotation marks inside the command by using backslashes:
\"

Otherwise the JSON parser will think that the " inside your command mark
the end of it, which will cause problems because then your JSON is invalid.

E.g.:

"command": "summon minecraft:armor_stand ~ ~ ~ {Unbreakable:1b,NoGravity:1b,
Tags:[\"positionStore\"],Invisible:1b}"
