### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DarkHydriegon** [apace100/origins-fabric#324]
![Screenshot_31](https://user-images.githubusercontent.com/85327898/120741865-7709ee00-c4bb-11eb-8f81-8b5cef3bc389.png)
![Screenshot_32](https://user-images.githubusercontent.com/85327898/120741869-7a04de80-c4bb-11eb-9cba-4d12253066bf.png)

**Comment by Alluysl** [comment]
The Fabric loader is Fabric, period, similary to Forge or Liteloader. The Fabric API is technically a mod, which adds some useful functionality (so most Fabric mods need it) but technically isn't necessary for *all* Fabric mods (Origins yes though), and isn't the issue here. So just update Fabric itself and you should be fine!

TL;DR: update Fabric, not the Fabric API
