### ISSUE TITLE
action_self doesn't accept anything other then primary keys

### ISSUE THREAD

**Issue by CyraLX** [apace100/origins-fabric#330]
I have tried changing the activation key of origins:action_self power but it doesn't seem to work no matter what I put in there
I know how it should be done but it just doesn't seem to work, possibly a bug?
It seems to work for other powers, but not for this one for some reason

**Comment by Emily-Rosaria** [comment]
I had a similar issue, but it was actually due to me not formatting it correctly.

I did:
```
"key": "key.[insert key here]"
```
Instead of:
```
"key": {
      "key": "key.[insert key here]"
}
```

So, without me seeming too ignorant, it would be worth checking your json structure is correct. Since otherwise, it will default to the primary key.

**Comment by CyraLX** [comment]
oh yeah i'm an idiot
I wonder why it  doesn't warn that it's a string not an object?

**Comment by apace100** [comment]
It doesn't warn you because simply using a string is the old way keys were specified. Back then, the only available keys were "primary" and "secondary". Thus, when you set the string as "primary", it will use the primary power key, while anything else would give you the secondary active power key.

I'll soon remove the old format, which will hopefully help others not to run into the same trap! Sorry for the bad communication and lack of information on this.
