### ISSUE TITLE
Conduit no longer functioning for Merling (1.17)

### ISSUE THREAD

**Issue by JackStoner** [apace100/origins-fabric#335]
Since the update, the conduit effect has started counting down as soon as merlings leave water, so there is no longer the effect of infinite water breathing in the conduit radius as there is supposed to be. Another player and I have both noticed this on my server since I updated it yesterday, and we would appreciate a fix as this is important to our efficiency in projects outside of water.

**Comment by Konoyuu13** [comment]
I would like to say this is still an issue with the newest update. The only thing working about the merling race it the ability to breathe underwater. Mining, Vision and speed underwater seem to be gone.

**Comment by apace100** [comment]
Fixed in 1.0.1.
If you are having problems with some powers not working, try running the `/power list <player>` command to see whether the powers are actually on the player, or just try switching to human and back to the origin. This was (or still is?) a bug that occurs sometimes (but it's unrelated to this issue). I'm sorry for the inconvenience!
