### ISSUE TITLE
Inchling health is reduced to half a heart upon travelling through a nether portal

### ISSUE THREAD

**Issue by soupyfish** [apace100/origins-fabric#341]
Inchling health is reduced to half a heart upon travelling through a nether portal, happens both ways.
Health returns to normal upon logging out and in again.
only seems to happen on a server, not in singleplayer
![image](https://user-images.githubusercontent.com/36567875/122134191-09a07a80-ce36-11eb-8b66-5b20fedb90fe.png)

**Comment by IceaPlayzPC** [comment]
My friend and I came across this as well - but instead our health was reduced to 4 upon entering the nether. We are using a custom origin that uses the arachnid's lowered health code, and i tested by changing my origin to arachnid and it seems that the arachnid's health itself is bugged, which is what we figured since my friend who made the datapack used default powers. Also serverside,
I can record a quick video to share if more info is needed

**Comment by soupyfish** [comment]
This also occurs with the piglin origin, with health reduced to 6 in the overworld instead of 8.

**Comment by IceaPlayzPC** [comment]
Good to know, it would be safe to assume that the feline origin is affected as well due to having one less heart of health, but i'll test that for sure when i'm able to.

**Comment by soupyfish** [comment]
fixed now
