### ISSUE TITLE
The server needs Apoli 1.0.0 Mod to run

### ISSUE THREAD

**Issue by okaysammyy** [apace100/origins-fabric#350]
Hello,

It states in the description of the mod that the mod has an already existing Apoli 1.0.0 mod within the code to run it however when i start up my server i get the error code that Apoli 1.0.0 mod is needed to access and run this server and therefore i cannot use the origins mod.

**Comment by PikeTheFish** [comment]
I am running into the same issue, but have not found a solution.

**Comment by apace100** [comment]
I assume you mean the server starts but connecting is impossible? This happens when you don't have Origins installed on your client. Both the server and all players need to install Origins! To check, you can try creating a singleplayer world to see whether Origins works there. If it doesn't, that means it isn't installed and you can't join Origins servers.
