### ISSUE TITLE
Cannot spawn in the Nether

### ISSUE THREAD

**Issue by kirkusmaximus** [apace100/origins-fabric#40]
[latest.log](https://github.com/apace100/origins-fabric/files/5360457/latest.log)

I spawned as a Piglin from the extra origin's mod. I got errors in the log and spawned in the overworld. Upon death i was unable to respawn. Hitting the respawn button triggered the same error and the only option is to go to the main menu.

I was requested to post the issue here and the extra origin's dev said it uses the same spawning method as Blazeborn.

**Comment by apace100** [comment]
Hey kirkusmaximus,

this sure is a weird bug. It seems like your Nether dimension is null (meaning it does not exist, or is not correctly linked up to the world). I do not really know what causes this. There have been reports of the Nether spawn sometimes not spawning you in the Nether, but this happens when it can't find a spawn point and does not cause an error or crash, it would simply not work.

What I've done is I put an additional check in the method, to see whether the Nether is null. If it is, it will print an error to the console now and just return a spawn in the overworld - this doesn't fix the problem completely, but it should at least not prevent anyone from respawning in the future.

I'll put that check in the next update.

**Comment by apace100** [comment]
It seems like this might not be a bug on my side, but on Vanilla's side: https://bugs.mojang.com/browse/MC-197860

According to someone on my Discord, multiple users complained about a bug like this which happens in certain mod packs, and causes the Nether to _not exist_, which in turn leads to the NetherSpawnPower causing problems, even though Origins is not the real cause.

**Comment by kirkusmaximus** [comment]
Is this bug supposed to be triggered on new world creation?
I was recreating a world off of a seed, you can see in the logs that this was first time generation. That said I did clone the minecraft instance from my main branch to test this issue out. Perhaps i should start fresh and use the same seed to see what the results are. If the fresh instance works this bug has further reaching implications than that bug report suggests.

I'll get back to you.

**Comment by kirkusmaximus** [comment]
Is this bug supposed to be triggered on new world creation?
I was recreating a world off of a seed, you can see in the logs that this was first time generation. That said I did clone the minecraft instance from my main branch to test this issue out. Perhaps i should start fresh and use the same seed to see what the results are. If the fresh instance works this bug has further reaching implications than that bug report suggests.

I'll get back to you.

**Comment by kirkusmaximus** [comment]
Yep as you suspected.

Creating a fresh instance instead of a copy fixed the issue. Used the same seed as well. That is one strange bug.

It does have more implications than previously stated. Looks like custom dimension datapacks mess with initial world creation.
