### ISSUE TITLE
SMP problem with origins

### ISSUE THREAD

**Issue by StarGuyR7** [apace100/origins-fabric#418]
the owner of an smp im playing in keeps trying to use the origins mod with apex hosting servers but it keeps crashing, how can he fix it?
here's the crash report he sent me
https://pastebin.com/AxkajLHn

**Comment by anima-ex-inani** [comment]
Reading the crash report, it appears that the problem with your servers is not due to Origins but instead, due to Fabric itself.

`Could not find required mod: fabric requires {minecraft @ [~1.17.1-rc]}` indicates that your Minecraft version is incompatible with the version Fabric is for. `1.17.1-rc` refers to the release candidates for 1.17.1. These are the versions Fabric is targeting. You are trying to run a different version of Minecraft.

Try updating Fabric to target the correct version.
