### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by catemiko** [apace100/origins-fabric#419]
Standing on soul sand with any boots equipped as Demon results Internal Server Error.

**Comment by catemiko** [comment]
![image](https://user-images.githubusercontent.com/28825932/131082201-e2b20f3e-619f-488b-bf37-159c9eefc7b7.png)

**Comment by toErIpNid** [comment]
I'd recommend also reporting that to the datapack author, seems more like they're thing.

**Comment by apace100** [comment]
Yeah, I'm not sure what that datapack or add-on even does. So I can't really help you here, sorry. Please report it to the datapack or add-on dev and tell them, that if they figure that the bug is on the side of Origins and not their add-on, they can feel free to report back here with more information. Thanks!
Closing this issue until then.
