### ISSUE TITLE
Every 1-2 minutes while I'm phantomized it just unphantomizes me for like 10-20 seconds

### ISSUE THREAD

**Issue by polygloid** [apace100/origins-fabric#469]
Is this intentional? If so ruining the main ability of phantom is NOT the way to balance this origin out

**Comment by apace100** [comment]
Since Origins 1.2.0, being phantomized requires you to have at least as much food as required for sprinting (3.5 chunks). I forgot to mention that in the changelog on CurseForge, sorry.

I'm up for a discussion about this balancing change, so if you have any _constructive_ feedback, feel free to leave it here or chat about it on the Discord server.

**Comment by polygloid** [comment]
OH. sorry, with that specified this is actually a really good balance to the phantom origin, it goes really well with the faster hunger it gets, thanks!
