### ISSUE TITLE
Origin 1.16.3-1.16.4 Race Change

### ISSUE THREAD

**Issue by litjohn50** [apace100/origins-fabric#48]
I Suggest a block/item that you can craft to change your race from one to another, without the use of op's admin commands.

This will help people who pick to live as fish the ability to one day enter the nether/end.

**Comment by apace100** [comment]
You can add a custom recipe for the `origins:orb_of_origin` (an item which lets you change your Origin) via a data pack. This will make it obtainable in survival.

I'm not going to add a recipe for that by default, because 1) it doesn't fit the general "idea" of the mod (you have those benefits and drawbacks and there's no way around them) and 2) I wouldn't want to dictate a balance - some want the item to be cheap, some want it expensive.

If you need an example for such a data pack, there is one available on the Discord server for Origins (invitation link can be found on the CurseForge page). You could download that and modify it to fit your needs, that might be the easiest way if you are inexperienced with data packs.
