### ISSUE TITLE
Vanilla client support (base functions)

### ISSUE THREAD

**Issue by CamperSamu** [apace100/origins-fabric#5]
Hi!
Can you please add a basic commands/chest gui interface for vanilla users?
I want to put this mod on a small server and play with friends and other people a Vanilla+ modpack and I'm trying to make everything server-side.
I would love to use this mod for a "vanilla" server like a plugin and looking at some videos and at the code, doesn't seem like it's possible yet.

**Comment by apace100** [comment]
Hi,

sorry, but this mod relies a lot on the client doing things. E.g. all the active powers would have to be rewritten to react to something that vanilla catches, such as sneaking, jumping, or something else, instead of a custom keybind. I could also not make use of the cooldown bars like I do now. Many powers also rely on the client knowing about them - e.g. the Elytrian's elytra flight power is only possible because of the client.

I hope you understand that making the mod completely server-side is just too much work for me, but you're welcome to work on it yourself if you want to.

**Comment by CamperSamu** [comment]
ok, thanks anyways!
