### ISSUE TITLE
[fabric 0.13.3-1.18.2 - origins 1.4.1] Startup Crash

### ISSUE THREAD

**Issue by VaelophisNyx** [apace100/origins-fabric#524]
[latest.log](https://github.com/apace100/origins-fabric/files/8501199/latest.log)
Origins causes a CTD at the mixins step when installed.

**Comment by apace100** [comment]
This crash report mentions Extra Alchemy as causing the issue, not Origins. Upon some research, it seems that Extra Alchemy 1.7.0 (the most recent version, and the one you have installed), is not marked as being compatible with MC 1.18.2.

Could you double check whether this is really an issue with Origins or just caused by Extra Alchemy (or any other mod of yours) not being compatible with 1.18.2?

**Comment by VaelophisNyx** [comment]
it was EA; apologies and thanks for the help
