### ISSUE TITLE
Water Protection book loottable

### ISSUE THREAD

**Issue by Disketaa** [apace100/origins-fabric#545]
**Water Protection** doesn't replace enchanted book in loottables, it adds itself in them with like another book.

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/76956762/168274808-c775b829-2124-4ec3-adb0-6d8ad1ee722a.gif)

**Comment by apace100** [comment]
This was a deliberate decision and is not a bug.

I decided to implement it this way because the water protection enchantment is not useful to every player. In a single-player world where you're not playing Blazeborn or Enderian, it is completely useless, not even being able to trade it with others.

In the past people complained that the book would spawn too often even though they don't need it that much, and that they feel water protection takes away from their loot, to which I replied with this implementation fact: it's not replacing another enchanted book you'd see in that place - without the mod installed, you would see _no book_ in that place, instead of a differently enchanted one.

**Comment by Disketaa** [comment]
Hm, maybe do a little config value that controls spawn-rate chance of this book?

**Comment by apace100** [comment]
That wouldn't change the mechanic of how the book is added to the loot table though.
Have you reported this just because you thought it was unintended behaviour, or do you actually have an _issue_ with how the book generates in the loot?

**Comment by Disketaa** [comment]
I just didn't know that book adds with another book. So If it intended all is good
