### ISSUE TITLE
Connection Lost: Invalid Player Data

### ISSUE THREAD

**Issue by ShadowDeveloper** [apace100/origins-fabric#548]
I'm on version 1.18.2, and I keep getting this error.
Setup:
1. Launch game
2. Create new world
3. Generate chunks
4. Error

Logs have so many errors, I've attached them here:
[latest.log](https://github.com/apace100/origins-fabric/files/8794526/latest.log)

Mods I'm using:
[mods.zip](https://github.com/apace100/origins-fabric/files/8794440/mods.zip)

**Comment by apace100** [comment]
This is because you installed so many origins that the code can't handle the size of the packets.
To fix this problem, either remove some origins, or install this mod: https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric

The other errors occur because some origins you have installed are faulty (e.g. refer to missing items). This is not caused by Origins itself as a mod, but by the datapacks/add-ons you use.

**Comment by ShadowDeveloper** [comment]
Working perfectly fine now, thank you!
