### ISSUE TITLE
Land and water breathing/evolutions

### ISSUE THREAD

**Issue by V-Celestial** [apace100/origins-fabric#68]
I've been playing around abit by making own origins but i wonder,
is there a way to make an origin that can breathe both on land and in water?
or even a sort of evolution system where when said conditions are met you can upgrade your origin with different paths?

I realize this is all just a big fantasy in my head right now, but if there is a way, i'd like to know how.

**Comment by apace100** [comment]
Yes. You can allow an Origin breathing on both land and water by making either a) a stacking_status_effect power, which grants the Water Breathing status effect when underwater, or b) an action_over_time power which performs a gain_air action continuously while underwater. Option B is preferred (because it doesn't interfere with potions).

You are able to define "evolutions" as you call them. This feature is called "origin upgrades". Basically, when an advancement you specify is made, a player will switch from their origin to another one. See the wiki for more information (at the bottom, where the keys are listed): https://github.com/apace100/origins-fabric/wiki/Defining-an-origin-in-JSON

**Comment by POPlol333** [comment]
Hi, i'm a bit late, but I'm trying what you said, i'm not really used to origins format, I don't have any error shown but I don't regain any air 
`
{
    "name": "Varanid's ability to breath underwater",
    "description": "Varanid member are able to breath underwater",
	"type": "origins:action_over_time",
    "action": "origins:gain_air",
	"interval": 1,
    "condition": {
		"type": "origins:submerged_in",
		"fluid": "minecraft:water"
	}
}
`

**Comment by POPlol333** [comment]
github format don't seem to love me too, here how it look in my json:
![image](https://user-images.githubusercontent.com/76914762/146249286-2ce56206-a3d7-4b59-9cb9-55a256e739f6.png)

**Comment by SunflowerDolls** [comment]
Did you ever figure it out? Me and my friend have been struggling with this for awhile now 🥲

**Comment by bloodywolf0** [comment]
Hi, for anyone who couldn't make the ability to breath on land and water here is the code.

{
  "type": "origins:water_breathing",
  "condition": {
    "type": "origins:submerged_in",
    "fluid": "minecraft:water"
  },
  "name": "water breathing",
  "description": "being mother's nature creation and a magical being give you the ability to breath under water"
}
