### ISSUE TITLE
Clients without the mod won't take damage (dedicated server)

### ISSUE THREAD

**Issue by dthusian** [apace100/origins-fabric#69]
I'm running a dedicated server with fabric, lithium, phosphor, and this mod. When a client that does not have origins installed joins, they're immune to all types of damage. This isn't just a client-side effect because the server seems to agree with it.

**Comment by apace100** [comment]
Yes, this happens because on the server-side, new players will not have chosen an origin. As long as players don't have an origin, they will be protected from damage. This was implemented to prevent them from taking damage while still in the origin selection screen. In the future, I hope to prevent people without the mod from joining.
