### ISSUE TITLE
Only Some Origins Available

### ISSUE THREAD

**Issue by nightlocust** [apace100/origins-fabric#715]
Versions:

    Java 1.20.2
    Fabric for 1.20.2
    Origins 1.20.2-1.11.3
    Pehkui 3.7.11+1.14.4-1.20.2

I booted up a singleplayer world, excited to try the origins in 1.20, and it only offered me half of the listed options professed in the mod. I wanted to play the Iceking, but it is not offered. What gives? Is there an issue in the config settings?

Loading it up alongside one of the other add-ons, (origins++,) all the vanilla options I originally had disappeared, but the Elytrian, (which had previously not been available,) showed up. ???

**Comment by Provismet** [comment]
Reporting a similar issue, but I believe I have a temporary fix. In my case: all of the vanilla origins showed up, but only 5 out of my 9 modded ones.

This issue did not occur when using an older version of the Fabric API (0.89.2+1.20.2), but did occur with the latest version of the API (0.91.2+1.20.2).  
I suspect the issue lies with how Origins is using the Networking API in the 1.20.2 version.

When using the newer API version an error about "identical IDs" appeared in the logs. Here are the logs for both trials:
- [0.89.2+1.20.2.txt](https://github.com/apace100/origins-fabric/files/13694578/0.89.2%2B1.20.2.txt)
- [0.91.2+1.20.2.txt](https://github.com/apace100/origins-fabric/files/13694580/0.91.2%2B1.20.2.txt)

**Comment by eggohito** [comment]
This should now be fixed in [Origins 1.12.0](https://www.curseforge.com/minecraft/mc-mods/origins/files/4976932)
