### ISSUE TITLE
1.20.2 Origins is missing phantom, merlingm, shulker, and avian origins

### ISSUE THREAD

**Issue by Iceheap** [apace100/origins-fabric#716]
I tested different game versions, and they have the origins, but 1.20.2 does not. This means this is an isolated issue for 1.20.2 only, I'm imagining. Why do I have origins missing?

**Comment by LocustThe** [comment]
spent some hours.. but managed to track down the issue.. i think.. 
Try using fabric-api-0.90.4+1.20.2.jar instead of the latest version.
This solved the issue for me.. I now see all the origins. 
Also loaded origins ++ and i now have 4 pages of origins to choose from :D

Current mods im running: 
altorigingui-1.0.2.jar
magic_origins v0.3.5 1.20.x.jar
Origins-1.20.2-1.11.3.jar
origins-plus-plus-2.2.jar
fabric-api-0.90.4+1.20.2.jar
Pehkui-3.7.11+1.14.4-1.20.2.jar
jei-1.20.2-fabric-16.0.0.28.jar

**Comment by Iceheap** [comment]
OH MY GOSH THANK YOU!! I only use the original origins mod, for anyone reading this in the future, so it's a origin specific issue, not caused by any other add ons to origins. But anyway THANK YOU SO MUCH LOCUST! I tried that and it worked, now my brother and I can play and he can choose whatever origin he wants. You're a life saver!!
