### ISSUE TITLE
Hello is there a way to move the resource bar from the mod?

### ISSUE THREAD

**Issue by PabloDnSS** [apace100/origins-fabric#733]
![2024-03-06_11 37 58](https://github.com/apace100/origins-fabric/assets/161372702/3b71f0b2-0194-48e5-89cb-df01fa22b512)

**Comment by eggohito** [comment]
If you have Modmenu installed, you can view the configurable settings the Origins mod provides in the "Mods" menu. Otherwise, you can modify the `power_config.json5` file, which can be found in your `.minecraft/config` folder. The relevant settings for moving the resource bars are the "HUD offset X" and "HUD offset Y" settings

**Comment by PabloDnSS** [comment]
Thank you for the answer but i have no power_config file in my config folder. i'm on forge 1.20.1

**Comment by eggohito** [comment]
> Thank you for the answer but i have no power_config file in my config folder. i'm on forge 1.20.1

In that case, you should be modifying the `.minecraft/config/apoli-client.toml` file instead. Also, the appropriate place to ask for assistance with the Forge port is https://github.com/EdwinMindcraft/origins-architectury/issues. This repository is for **Fabric**
