### ISSUE TITLE
[Origins 1.20.2-1.12.7 / Apoli 2.11.7] modify_player_spawn power type cannot load dimensions and fails to load

### ISSUE THREAD

**Issue by MoriyaShiine** [apace100/origins-fabric#743]
Fabric Loader Version: 0.15.9
Fabric API Version: 0.91.6+1.20.2
Origins Version: 1.12.7

No other mods installed

The modify_player_spawn power type doesn't function, and errors in the log that the dimension it attempts to spawn the player in is not in the registry. This affects Blazeborn by default, but any origin using this power type will also spawn in the Overworld instead of the intended spawn.

Log (starting on line 103): https://gist.github.com/MoriyaShiine/dc67f8d4d868203094818a3b9903099a

**Comment by eggohito** [comment]
This is such a weird issue; it seems like vanilla dimensions are not being registered in the dynamic registry for dimensions on world creation screen at all, as it's empty (I checked on `SaveLoading#load`.) It'll only be occupied if there are data packs that either include custom dimensions, or overrides the vanilla ones (like Terralith)

The only solution I can think of is to do some sort of "whitelist" for vanilla dimensions, so that powers (or any reloadable data that uses Calio for serialization) won't throw the error if it's specified 🤔
