### ISSUE TITLE
[1.20.1] `origins:edible_item` doesn't work

### ISSUE THREAD

**Issue by LTCatt** [apace100/origins-fabric#746]
![image](https://github.com/apace100/origins-fabric/assets/40348278/0cba6b0f-4925-4bf0-a9f4-c70d2437ec84)

Using examples in https://origins.readthedocs.io/en/latest/types/power_types/edible_item/
Version: 1.20.1-1.10.1

**Comment by eggohito** [comment]
The `edible_item` power type was introduced in Origins 1.11.0, which is for Minecraft 1.20.2. There are plans on officially backporting stuff, but there's an issue that's blocking the backport, so there'll be no ETA

**Comment by LTCatt** [comment]
Maybe you could point out in the documentation the range of versions it's currently in effect, or it can be very confusing.
Thanks for the reply!

**Comment by LTCatt** [comment]
Hi, is it ok now?

**Comment by DarianLStephens** [comment]
Doesn't seem to be, even now in 2026.
There probably won't be an official backport at this point, which is a shame because _so_ much awesome stuff was added in the 1.20.2 version and I've been caught out multiple times now, having an entire power planned out which relies on something that wasn't added yet, and then having to completely rethink it because it's not possible on the version I'm using.

1.20.2 is such an awkward version for this, too. Most mods just skip or ignore it, with the majority stuck on 1.20.1 or going straight to 1.21.1.

**Comment by bulutthecat** [comment]
Someone needs to reopen this as an issue. Its still a valid problem, and prevents alot of later origins from working on 1.20.1 (which is still a widely used major modding version). Back-port from 120.2 to 1.20.1 shouldn't be difficult, although there were major version breaking changes in the Fabric API not many of them effect power types like these, at least some effort should be put into back-porting the less difficult powers.

If not, I will look into it myself on a fork.
